name: "Coverity"

on:
  workflow_dispatch:
  #push:
    #branches: [ master, develop ]
  #pull_request:
    #branches: [ master, develop ]
#  schedule:
#    - cron: '21 20 * * 5'

jobs:
  convert:
    name: Convert and upload coverity results
    runs-on: ubuntu-22.04
    permissions:
      # required for all workflows
      security-events: write
      # required for workflows in private repositories
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Convert Coverity Results to SARIF
      uses: gautambaghel/coverity-scan-results-to-sarif@a4c2c4964e93a9bc429656fe5c212e20c02538df  # master
      with:
        pipeline-results-json: coverity-results.json
        output-results-sarif: coverity-results.sarif

    - name: Upload SARIF file to GitHub UI
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: coverity-results.sarif
