name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  cpplint:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run cpplint
      run: |
        tox -e lint
