name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  cpplint:

    runs-on: ubuntu-latest
    permissions:
      # required for workflows in private repositories
      actions: read
      contents: read
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run cpplint
      run: |
        tox -e lint
